# --- COMA specific parameters ---

action_selector: "multinomial"

# epsilon greedy 
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000

mask_before_softmax: False

runner: "parallel"

# Replay buffer
buffer_size: 150
batch_size_run: 8
batch_size: 8

# env_args:
#   state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

# learning rate
lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "policy_gradient_v2"
mixer: "qmix"
q_nstep: 0  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
lam: 0.95
ent_coef:
vf_coef: 0.1
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64



# agent
residue: False
num_blocks: 5
n_head: 1

mac: "ppo_mac"
agent: "trans_ppo"
adj: [[1, 1, 0, 0, 0],
      [1, 1, 1, 0, 0],
      [0, 1, 1, 1, 1],
      [0, 0, 1, 1, 0],
      [0, 0, 1, 0, 1]]
name: "trans_vmix_pg_a2c"
